# Generated by Django 2.2.11 on 2020-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titled', models.CharField(max_length=300, unique=True)),
                ('contentd', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
