# Generated by Django 2.2.11 on 2020-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviarApp', '0002_anpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anpost',
            name='contentd',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
